### ISSUE TITLE
Why const AL_NO_ERROR* = false?

### ISSUE THREAD

**Issue by demotomohiro** [treeform/openal#1]
`AL_NO_ERROR` is defined as `const AL_NO_ERROR* = false` in `src/openal.nim`.
But it is defined `#define AL_NO_ERROR 0` in al.h.
As type of the return value of `alGetError()` is `ALenum`, I have to cast it to compare to `AL_NO_ERROR`.
Can you change it to `AL_NO_ERROR* = 0`?

**Comment by treeform** [comment]
You totally right. I don't know why its false. Some sort of c2nim issue.

Fixed: https://github.com/treeform/openal/commit/f40fe6e1e131ec27025b54234c99e4f1ccd2a3dc
